# Config for user's tiles module integrated into eyegaze.
# Timing is copied from hybrid-bci-p300-ssvep.zip, tuned for the photodetector test.

WINDOW_SIZE = [1600, 900]
WINDOW_COLOR = "#202020"
FULLSCREEN = False

# Perimeter layout for wide screen: 9 tiles around the edges.
PERIMETER_TOP_COUNT = 4
PERIMETER_BOTTOM_COUNT = 3
PERIMETER_LEFT_COUNT = 1
PERIMETER_RIGHT_COUNT = 1
PERIMETER_EDGE_MARGIN_PX = 105
PERIMETER_CORNER_MARGIN_PX = 180
TILE_TOTAL = PERIMETER_TOP_COUNT + PERIMETER_BOTTOM_COUNT + PERIMETER_LEFT_COUNT + PERIMETER_RIGHT_COUNT

GRID_SIZE = 3
TILE_DISPLAY_SCALE = 1.0
TILE_SIZE_PX = 250
TILE_SPACING_PX = 30
TILE_DEFAULT_COLOR = "white"
TILE_LINE_COLOR = "#aaaaaa"

BUTTON_WIDTH = 150
BUTTON_HEIGHT = 54
START_BUTTON_POS = (-95, -200)
STOP_BUTTON_POS = (85, -200)

PANEL_X_FRACTION = 0.52
PANEL_FIRST_ROW_Y = 245
PANEL_ROW_DY = 48
PANEL_LABEL_OFFSET = -185
PANEL_TB_W = 135
PANEL_TB_H = 38
PANEL_LETTER_H = 20

OPERATOR_HINT_Y = -395
OPERATOR_HINT_H = 18

# --- Photodetector/P300 timing from uploaded hybrid-bci-p300-ssvep.zip ---
# One full target cycle: 9 × (0.10 + 0.10) + 0.8 = 2.6 s, target frequency ≈ 0.385 Hz.
DEFAULT_FLASH_DURATION = 0.10
DEFAULT_ISI = 0.10
DEFAULT_INTER_BLOCK_S = 0.8
DEFAULT_SEQUENCES = 12

DEFAULT_CUE_S = 2.0
DEFAULT_READY_S = 1.5
DEFAULT_TARGET_ID = 0

CUE_MIN = 0.3
CUE_MAX = 10.0
READY_MIN = 0.2
READY_MAX = 10.0
ISI_MIN = 0.01
ISI_MAX = 2.0
FLASH_MIN = 0.01
FLASH_MAX = 0.5
INTER_BLOCK_MIN = 0.0
INTER_BLOCK_MAX = 5.0
SEQUENCES_MIN = 1
SEQUENCES_MAX = 40

# Target cue and flash color: white for photodetector.
CUE_COLOR = "white"
STIM_COLOR = "black"

FIXATION_CROSS_SIZE = 35
FIXATION_CROSS_COLOR = "black"

# Eye-gaze overlay.
GAZE_INFO_POS = (-640, 250)
GAZE_INFO_HEIGHT = 32
GAZE_INFO_WRAP_WIDTH = 1100
GAZE_DOT_RADIUS = 18

DISTANCE_GAZE_DOT_SIZE_ENABLED = True
DISTANCE_GAZE_DOT_UPDATE_THRESHOLD_CM = 2.5
DISTANCE_GAZE_DOT_REFERENCE_CM = 0.0
DISTANCE_GAZE_DOT_MIN_SCALE = 0.70
DISTANCE_GAZE_DOT_MAX_SCALE = 1.60

YELLOW_SPOT_ANGLE_DEG = 8.0
YELLOW_SPOT_REFERENCE_DISTANCE_CM = 80.0
YELLOW_SPOT_DISTANCE_SIZE_ENABLED = True
YELLOW_SPOT_UPDATE_THRESHOLD_CM = 2.5
YELLOW_SPOT_MIN_RADIUS_PX = 8.0
YELLOW_SPOT_MAX_RADIUS_PX = 260.0
YELLOW_SPOT_FILL_COLOR = "red"
YELLOW_SPOT_LINE_COLOR = "white"
SCREEN_WIDTH_CM = 60.0
SCREEN_HEIGHT_CM = 33.0
YELLOW_SPOT_OPACITY = 0.45

P300_BRIDGE_ENABLED = True
P300_DECISION_PATH = "data/p300_bridge/latest_decision.json"
P300_DECISION_MAX_AGE_S = 30.0

SCREEN_INDEX = 1
